# 所有环境共用配置
spring:
  application:
    name: user-center
  profiles:
    active: prod

mybatis:
  mapper-locations: classpath:mappers/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

---
# 开发环境
spring:
  profiles: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 18896727773

  cloud:
    nacos:
      discovery:
        server-addr: 81.68.78.224:8848
#        cluster-name: BJ

server:
  port: 8081

---
# 生产环境
spring:
  profiles: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: QWer!@34

  cloud:
    nacos:
      discovery:
        server-addr: 81.68.78.224:8848
#       cluster-name: BJ

server:
  tomcat:
    max-threads: 300
    max-connections: 1000

  port: 8083
