# 开发环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tsien16.com:3306/user_center?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 18896727773

  cloud:
    nacos:
      discovery:
        server-addr: tsien16.com:8848
    stream:
      rocketmq:
        binder:
          name-server: tsien16.com:9876

logging:
  level:
    com.tsien: debug

server:
  port: 8081