# 生产环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: QWer!@34

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #       cluster-name: BJ
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        input:
          destination: add-bonus
          # 如果不设置，应用启动不了，其它mq可以不设置
          group: add-bonus
        my-input:
          destination: stream-my-topic
          group: stream-my-topic

logging:
  level:
    com.tsien: debug

server:
  tomcat:
    max-threads: 300
    max-connections: 1000

  port: 8083