# 所有环境共用配置
spring:
  application:
    name: user-center
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mappers/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl